export default {
  name: "compliment",
  description: "Give a random compliment to make someone's day better!",
  aliases: ["praise",
    "nice"],
  cooldown: 4000,
  category: "🧩 Fun",
  execute: async (args, message) => {
    const compliments = [
      "You're like a software update; you make everything better!",
      "You’re the CSS to my HTML – you make everything beautiful!",
      "You light up the room like a 100-watt bulb.",
      "You're a genius! You even know how to use this bot.",
      "You're the reason the sun comes out every day. Probably.",
      "Your kindness is a gift to everyone around you.",
      "If you were a vegetable, you'd be a 'cute-cumber.'",
      "You're like a coffee in the morning — you brighten everyone's day.",
      "You're a treasure, and everyone is lucky to know you.",
      "You're not just a pretty face — you're brilliant, too!",
      "You bring a smile to everyone's face, even on the toughest days.",
      "You're a shining star, and you make the world better just by being in it.",
      "You're like the perfect bug fix — you make everything run smoother.",
      "Your positivity is contagious, and it's impossible not to feel happy around you.",
      "You're a breath of fresh air in a room full of stale ideas.",
      "You have the rare ability to make every situation better just by being you.",
      "Your creativity knows no bounds — it's inspiring!",
      "You bring out the best in everyone around you.",
      "You're like a human ray of sunshine, spreading warmth wherever you go.",
      "Your laughter is the best part of any day.",
      "You're a coding wizard — everything you touch turns into magic.",
      "You’re the reason the Wi-Fi signal is so strong — everyone’s connected to your awesomeness!",
      "You're a work of art, and the world is better with you in it.",
      "You're like a great piece of code: clean, efficient, and just brilliant.",
      "You're the emoji that says it all — you're awesome!",
      "You're like the perfect algorithm, always finding the best solution.",
      "You're the kind of person who makes others believe in magic.",
      "You're the best teammate anyone could ask for.",
      "You're not just another line of code — you're the entire program!",
      "You make the world a better place, one kind act at a time.",
      "You're the kind of person who makes the impossible seem possible.",
      "You're like a good variable — always adaptable and reliable.",
      "You're the heartbeat of any team, keeping things running smoothly.",
      "You're like a breath of fresh air after a long day of debugging.",
      "You're the type of person who makes every day feel like a win.",
      "You're the best part of my day, every single day.",
      "You’re like a solid framework — everyone can build on your strength.",
      "You make life more colorful, like a full spectrum of bright hues.",
      "Your intelligence shines like a lighthouse guiding others to success.",
      "You're the key to every puzzle — everything makes sense with you.",
      "You’ve got the perfect blend of smarts and charm.",
      "You're a gem in a sea of stones.",
      "Your sense of humor is the perfect patch to any problem.",
      "You're a true original — one of a kind and simply irreplaceable.",
      "You make the world a little bit brighter, just by being in it.",
      "You’re the kind of person who makes a difference without even trying.",
      "You're like a great design pattern — always effective and never out of place.",
      "You're the best kind of rare — unique and impossible to replicate.",
      "You bring the perfect balance of logic and creativity.",
      "You're the type of person who makes every challenge feel like an opportunity.",
      "You’re a perfect balance of creativity and precision — truly exceptional.",
      "You're the spark that lights up every room you enter.",
      "Your presence is like a warm hug, comforting and full of positivity.",
      "You're like the most efficient algorithm — always getting results.",
      "You're an inspiration to everyone who gets to know you.",
      "You're a walking, talking ray of sunshine.",
      "You make every day feel like an adventure, full of endless possibilities.",
      "You're the magic ingredient that makes everything better.",
      "You're an invaluable treasure to everyone who knows you.",
      "You're like a good book — everyone wants to know your story.",
      "You're a star that makes everything around you shine brighter.",
      "You’re a superpower in human form — unstoppable and amazing.",
      "You're the kind of person who makes every situation better.",
      "You turn ordinary moments into extraordinary ones.",
      "Your kindness is like an unlimited resource — always available and always needed.",
      "You’re like the perfect partner in crime, making every challenge fun.",
      "You're the glue that holds everything together, no matter the circumstances.",
      "You’re like a wonderful mystery, always keeping us guessing and inspired.",
      "You're the best part of any team — the one who brings everyone together.",
      "You’re the spark that lights up even the darkest days.",
      "You’re the type of person who makes every day feel like a new adventure.",
      "You carry a universe within you, with stars that shine brighter than any in the sky.",
      "Your thoughts are like constellations, connecting ideas in the most mesmerizing patterns.",
      "You have the kind of soul that poets spend their lives trying to describe.",
      "The way you see the world turns ordinary moments into timeless art.",
      "Your presence feels like the first ray of dawn — warm, hopeful, and full of possibilities.",
      "You’re like a rare book — every page of you is worth discovering and cherishing.",
      "There’s a quiet strength in you, like the ocean before it meets the shore.",
      "You speak with a wisdom that feels like it comes from ancient, sacred places.",
      "Your laughter dances in the air, lingering like the sweetest melody.",
      "You’re not just a chapter; you’re the entire story that people never want to end.",
      "You have a way of making the world feel as if it’s blooming in slow motion.",
      "Your curiosity is a key that unlocks doors others don’t even notice.",
      "You’re like the moon — even when you’re not fully visible, your presence is felt everywhere.",
      "Your kindness is a ripple that turns into waves, touching places you may never see.",
      "You wear your heart like an open sky — vast, inviting, and full of wonder.",
      "Your words have the ability to paint colors on the grayest of days.",
      "You hold secrets in your eyes that feel like they could rewrite the universe.",
      "You have the kind of resilience that bends but never breaks, like the tallest trees in a storm.",
      "Your mind is an endless labyrinth of beautiful ideas waiting to be explored.",
      "The energy you bring into a room feels like the moment just before a symphony begins.",
      "You’re like a rare flower blooming in unexpected places, surprising and enchanting everyone.",
      "Your dreams have the kind of gravity that pulls others into orbit around you.",
      "You carry a quiet magic that whispers to anyone who’s lucky enough to notice.",
      "You’re like a kaleidoscope, always shifting and revealing new facets of brilliance.",
      "Your spirit is like a river — calm on the surface but carrying immense depth beneath.",
      "You’re the kind of mystery that makes life feel thrilling and full of discovery.",
      "The way you care for others feels like sunlight touching everything it reaches.",
      "Your perspective is like a prism, showing beauty in angles most people overlook.",
      "You have a way of finding treasure in the most unexpected places.",
      "Your creativity is like a lighthouse, guiding others through uncharted waters.",
      "You remind people that there’s magic in the world, even in the smallest things.",
      "Your passion burns like a fire that warms everyone it touches.",
      "You’re like a quiet revolution, changing the world in ways that aren’t always seen but always felt.",
      "Your voice carries the weight of the stories you’ve lived, and they’re worth hearing.",
      "You make life feel like an adventure worth embarking on every single day.",
      "The spark in your eyes feels like it could ignite entire galaxies.",
      "You’re the kind of person whose impact echoes long after they leave the room.",
      "Your authenticity is like rare gold — unpolished but utterly priceless.",
      "You move through life like a dancer, gracefully navigating even the hardest steps.",
      "Your soul feels like a tapestry woven with threads of courage, love, and dreams.",
      "You’re like rain in the desert — unexpected, life-giving, and unforgettable.",
      "You see beauty where others see chaos, and that’s your superpower.",
      "Your smile feels like a secret sunrise that only a few are lucky enough to witness.",
      "You’re like a puzzle that keeps revealing new pieces, each more fascinating than the last.",
      "Your heart beats with a rhythm that seems to sync with the pulse of the universe.",
      "You leave traces of wonder wherever you go, like footsteps in fresh snow.",
      "You’re like a rare gem — not just valuable but deeply treasured.",
      "You have the ability to turn silence into poetry and chaos into harmony.",
      "Your existence feels like a gentle reminder that miracles happen every day.",
      "You’re not just a person — you’re a symphony, and every note is extraordinary."];

    const target = args.length ? args.join(" "): "you";
    const randomCompliment = compliments[Math.floor(Math.random() * compliments.length)];

    await message.reply(`✨ ${target.replace(args[0], "")}, ${randomCompliment}`);
  },
};